### PR TITLE
Fix step failure message

### LINKED ISSUE #66: Step failure output mangled
**Describe the bug**

If a step fails because the step function returned an error, the output is mangled with `fmt.SPrintf()` error output.

For example, say the step is `And 2 items posted`.  If the function returns `fmt.Errorf("expected %d items, received %d", n, actual)`, then the output would be

> gobdd.go:377: And %!(EXTRA string=2 items posted, *errors.errorString=expected 2 items posted, received 0) 

**Expected behavior**

Prints out the step and the error clearly formatted. Something like:

> gobdd.go:377: And 2 items posted: expected 2 items posted, received 0

### PR DESCRIPTION
**Pull request by sblundy**
Fixes #66

When a step failed, the step's Kind was being passed in as the format param. This wasn't a valid format and so an Printf error was being printed out resulting in a garbled error. Added a proper format param in front of the Kind. Also extracted the function that runs each step so it could be unit tested properly

### CODE REVIEW

File: gobdd.go [hunk 1]
```diff
@@ -352,38 +353,42 @@ func (s *Suite) runStep(ctx context.Context, t *testing.T, step *messages.Gherki
...
+		paramType := paramType(v, inType)
+		in = append(in, paramType)
+	}
+	retValues := d.Call(in)
+	v := retValues[1]
 
-	return ctx
+	if !v.IsNil() {
+		err := v.Interface().(error)
+		t.Errorf("%s %s: %v", step.Keyword, step.Text, err)
```
Comment (sblundy) [inline gobdd.go]: This is the fix, just added the first parameter. The rest is all refactoring

File: gobdd_test.go [hunk 2]
```diff
@@ -83,6 +85,32 @@ func TestInvalidFunctionSignature(t *testing.T) {
 	}
 }
 
+func TestFailureOutput(t *testing.T) {
+	testCases := []struct {
+		name     string
+		f        interface{}
+		expected []string
```
Comment (bkielbasa) [inline gobdd_test.go]: expected what? I'd put a more clear name of it. Expected errors? `expectedErrs`?

File: gobdd_test.go [hunk 3]
```diff
@@ -119,30 +147,43 @@ func fail(ctx context.Context) (context.Context, error) {
...
 	return ctx, nil
 }
 
 type mockTester struct {
 	fatalCalled int
+	errors      []string
 }
 
-func (m mockTester) Log(...interface{}) {
+func (m *mockTester) Log(...interface{}) {
```
Comment (bkielbasa) [inline gobdd_test.go]: why did you put pointers here? If the function doesn't change anything I never put pointers :) https://golang.org/doc/effective_go.html#pointers_vs_values

File: gobdd.go (hunk 1 above)
Comment (bkielbasa) [reply gobdd.go]: just to highlight it, before the change it looked like that


```go
t.Errorf(step.Keyword, step.Text, err)
```

File: gobdd_test.go (hunk 2 above)
Comment (sblundy) [reply gobdd_test.go]: Good suggestion!

File: gobdd_test.go (hunk 3 above)
Comment (sblundy) [reply gobdd_test.go]: Because, in most cases, anyone adding an implementation would be changing something. Value receivers would quietly prevent the changes from persisting, leading to subtle bugs. I got bit by this while working on this bug, so I made sure the next guy wouldn't be. 

Also, [Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#receiver-type) says

>  If in doubt, use a pointer
